### PR TITLE
Href: Added option to include filter values into link

### PR DESCRIPTION
**Pull request by foxycode**
I'd like to add this feature to be able redirect back to grid with proper filters set. I am not sure if it is possible to compose filter params for link in better way. Let me know if I can done some part of this better.

### CODE REVIEW

**Comment by o5** [comment]
Did you to tried mark grido component as persistent?

**Comment by foxycode** [comment]
@o5 If I set it as persistent, than parameters are used in all presenter links which is not desirable.

**Comment by o5** [comment]
Again: Did you tried? :) 

For example, if you have a presenter ArticlePresenter where you have grido as component marked as persistent, **only** links to ArticlePresenter (not in all) will contain grido params. You probably define grido as persistent in parent of presenters?

**Comment by foxycode** [comment]
@o5 Ok, I tried now and it is not working. Even if it is was, I am limited to current presenter and I can't exclude some presenter actions. There is no simple way how to reset persistent parameters do default as I know.

**Comment by o5** [comment]
Sorry, but I'm closing. 

This is very specific use case and you can also resolve this by `$grid->setRemeberState()`

**Pull request closed without merging**
