### PR TITLE
Tests improvements

### PR DESCRIPTION
**Pull request by TomasVotruba**
- [x] make tester run out of the box - skip sorting out list of required and missing extensions
    - 1. run: `vendor/bin/tester tests -s -c tests/php-unix.ini`
    - 2. profit

- [x] make use of composer `autoload-dev`

### CODE REVIEW

**Comment by o5** [comment]
Thanks for participation! 

ad 1) I don't understand why is this important. Do you have a problem with run tests? In which environment? I've a standard php osx environment and I don't have any problem. Travis don't have any problem too.

ad 2) I think, this is required part for step 3.
ad 3) Nice idea! I have nothing against it.

**Comment by TomasVotruba** [comment]
1) That expected, otherwise config would be present by default. I don't have enabled sqlite3 extension, since I don't use it. Thus I have to add it or make config to take care of it.

OS or Travis are not the issue, different local php.ini files are. Try to disable one of those extensions locally and run the tests.

3) Great, I'll check it.

**Comment by TomasVotruba** [comment]
3) Bad news everyone! Looks like Tester [can find only *.phpt files](https://github.com/nette/tester/blob/master/Tester/Runner/Runner.php#L23), which is not compatible with composer PSR-4 autoloading.

Any suggestions?

PHPUnit tests would be ok.

**Comment by o5** [comment]
PHPUnit also has report in clover format required by Scrutinizer
(currently nette tester clover format is different) . But I dont know, how
long spent rewrite tests to PHPUnit.

Dne úterý 10. února 2015 Tomáš Votruba <notifications@github.com> napsal(a):

> 3) Bad news everyone! Looks like Tester can find only *.phpt files
> <https://github.com/nette/tester/blob/master/Tester/Runner/Runner.php#L23>,
> which is not compatible with composer PSR-4 autoloading.
>
> Any suggestions?
>
> PHPUnit tests would be ok.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/o5/grido/pull/180#issuecomment-73752964>.
>


-- 

Regards
Petr Bugyík
--------------------------------
mobile: +420 739 217 173
www: http://petr.bugyik.cz

**Comment by TomasVotruba** [comment]
I prefer PHPUnit too and I've rewritten around 12 packages lately, so I can find out for you :).

**Comment by TomasVotruba** [comment]
One question, do you require these class docblocks? It pretty much duplicates class name and I don't see any added information in it.

```php
/**
 * Test helper.
 *
 * @author     Petr Bugyík
 * @package    Grido\Tests
 */
class Helper
```

**Comment by o5** [comment]
Probably not :))

Dne středa 11. února 2015 Tomáš Votruba <notifications@github.com>
napsal(a):

> One question, do you require these class docblocks? It pretty much
> duplicates class name and I don't see any added information in it.
>
> /** * Test helper. * * @author     Petr Bugyík * @package    Grido\Tests */class Helper
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/o5/grido/pull/180#issuecomment-73947553>.
>


-- 

Regards
Petr Bugyík
--------------------------------
mobile: +420 739 217 173
www: http://petr.bugyik.cz

**Comment by milo** [comment]
> Looks like Tester can find only *.phpt files, which is not compatible with composer PSR-4 autoloading

You can use mask like `vendor/bin/tester 'tests/**/*Test.php` and glob expands it. Expanding expressions depends on your shell capability.

Why is the PSR-4 is needed by composer/PHPUnit? Tester does not need it.

**Comment by TomasVotruba** [comment]
@milo PSR-4 is successor of deprecated PSR-0

**Comment by TomasVotruba** [comment]
@o5 I'm almost done, just solve few spaces/tabs issues. Current coverage is 83 % just FYI :)

**Comment by milo** [comment]
@TomasVotruba Sure. I mean why you need autoloading for TestCase classes?

**Comment by TomasVotruba** [comment]
@milo To avoid any require/include when I need [another class/file](https://github.com/o5/grido/blob/bf8659cd63607203df704c9344195c22878daf04/tests/DataSources/NetteDatabase.phpt#L16). 

This approach suggest tests should have lower code quality than application code. Which is not necessary.

**Comment by o5** [comment]
> Current coverage is 83 % just FYI :)

It was 92% with Nette Tester! I don't want PHPUnit :D

**Comment by TomasVotruba** [comment]
@o5 I got stuck with request and I don't want to invest any more time in it. So this can be merged and I can push it to new branch, if you'd be interested in finishing it.

**Comment by o5** [comment]
Thanks!

**Comment by TomasVotruba** [comment]
Thank you :)

**Comment by pepakriz** [comment]
:+1:

**Comment by o5** [comment]
> I can push it to new branch, if you'd be interested in finishing it.

@TomasVotruba: Do you still have it?

**Comment by TomasVotruba** [comment]
Nope, I didn't see any reply, so I thought you're not interested.

**Pull request closed without merging**
