### PR TITLE
fix deprecated stuff

### PR DESCRIPTION
**Pull request by Ciki**

### CODE REVIEW

**Comment by o5** [comment]
to je pro nette 2.4?

**Comment by Ciki** [comment]
Ano

2016-05-24 9:53 GMT+02:00 Petr Bugyík <notifications@github.com>:

> to je pro nette 2.4?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/o5/grido/pull/278#issuecomment-221193068>
>



-- 
S pozdravom / Best Regards
Ing. Matúš Matula

**Comment by Ciki** [comment]
ahoj @o5 je s tymto PR nejaky problem, aby bol mergnuty?

**Comment by o5** [comment]
@Ciki: sorry, byl jsem tyden mimo. Muzes to pls zkusit s aktualni master verzi Grido a Nette 2.4 jestli jsem na neco nezapomnel? Diky

**Comment by Ciki** [comment]
Ahoj, vyzera to byt OK. Dik

**Pull request closed without merging**
