### PR TITLE
Property accessor

### PR DESCRIPTION
**Pull request by TomasVotruba**
Ref: #179 

- [x] use Symfony\PropertyAccess by default
- [x] drop custom ArrayObjectAccessor (already included in Symfony one)
- [x] add tests

If you have any other uses cases, let me know.

Otherwise I'd suggest to drop ArrayObjectAccessor (see second checkbox).

### CODE REVIEW

**Comment by o5** [comment]
Good job, thanks! 

I'm thinking about removing whole property accessor wraper (and methods <code>$grid->setPropertyAccessor()</code>, <code>getPropertyAccessor()</code>). Grido uses only <code>getProperty()</code> method and "all magic" is in [this sugger](https://github.com/TomasVotruba/grido/commit/a469356491df6d4e024f65a20b8cc1e8fe532df5#diff-3fa77436c6caf5cae9bf1c3e3501ed1bR42). Am I wrong?

**Comment by TomasVotruba** [comment]
You're correct. That was my next step, so yes!

**Comment by TomasVotruba** [comment]
Something like this https://github.com/TomasVotruba/grido/commit/eb681c648bbe07d0bcb2c2b324562669cd6189f7 ?

**Comment by TomasVotruba** [comment]
:+1:

**Comment by TomasVotruba** [comment]
Could you also tag new version pls?

**Comment by o5** [comment]
Next release will be [2.1.0](https://github.com/o5/grido/milestones).

**Pull request merged**
